spring.config.import=file:./.env[.properties]

#DATABASE
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#JPA
spring.application.name=mr-world-theme-tour-backend
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

# JWT
app.jwt.secret-base64=${JWT_SECRET_BASE64}
app.jwt.issuer=mr-world-theme-tour-backend
app.jwt.audience=mr-world-theme-tour-api
app.jwt.access-token-ttl=15m
app.cors.allowed-origins=http://localhost:5173
